# Generated by Django 4.1.2 on 2023-04-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('numero_personas', models.IntegerField()),
                ('telefono_contacto', models.CharField(max_length=20)),
                ('email_contacto', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'reservas',
                'managed': False,
            },
        ),
    ]
